// src/lib/sessions.ts
// Persistence + read layer for completed coach runs. The graph itself is
// stateless; this is where a finished run is written to coach_sessions /
// coach_specialist_calls so it can be reviewed later at /coach/history.

import { desc, eq } from "drizzle-orm";
import { getDb } from "@/lib/db";
import { coachSessions, coachSpecialistCalls } from "@/db/schema";
import type {
  Agent,
  Citation,
  FinalAnswer,
  FindingsMap,
  RoutingDecision,
  SpecialistFinding,
  ToolCallRecord,
} from "@/state";

export interface PersistSessionArgs {
  /** The session UUID generated by the query route; reused as the row id. */
  sessionId: string;
  query: string;
  routing: RoutingDecision | null;
  findings: FindingsMap;
  finalAnswer: FinalAnswer | null;
  langsmithRunId: string | null;
}

/** A coach_sessions row, with the routing jsonb typed back to its shape. */
export interface SessionRow {
  id: string;
  query: string;
  routing: RoutingDecision | null;
  finalAnswerText: string | null;
  consultedAgents: string[];
  langsmithRunId: string | null;
  createdAt: Date;
}

/** A coach_specialist_calls row, with the jsonb columns typed back. */
export interface SpecialistCallRow {
  id: string;
  agentName: string;
  subQuestion: string;
  findingText: string;
  citations: Citation[];
  toolCalls: ToolCallRecord[];
  durationMs: number;
  createdAt: Date;
}

export interface SessionDetail extends SessionRow {
  calls: SpecialistCallRow[];
}

/**
 * Write a completed coach run to the database. The supervisor run and each
 * specialist finding become one coach_sessions row plus one
 * coach_specialist_calls row per finding. Best-effort: callers wrap this so a
 * persistence failure never breaks the live response.
 */
export async function persistSession(args: PersistSessionArgs): Promise<void> {
  const db = getDb();

  const consultedAgents =
    args.finalAnswer?.consultedAgents ??
    (Object.keys(args.findings) as Agent[]);

  await db.insert(coachSessions).values({
    id: args.sessionId,
    query: args.query,
    routing: args.routing,
    finalAnswerText: args.finalAnswer?.text ?? null,
    consultedAgents,
    langsmithRunId: args.langsmithRunId,
  });

  const findings = Object.values(args.findings).filter(
    (f): f is SpecialistFinding => Boolean(f),
  );
  if (findings.length > 0) {
    await db.insert(coachSpecialistCalls).values(
      findings.map((finding) => ({
        sessionId: args.sessionId,
        agentName: finding.agent,
        subQuestion: args.routing?.subQuestions[finding.agent] ?? "",
        findingText: finding.text,
        citations: finding.citations,
        toolCalls: finding.toolCalls,
        durationMs: finding.durationMs,
      })),
    );
  }
}

type RawSessionRow = typeof coachSessions.$inferSelect;
type RawCallRow = typeof coachSpecialistCalls.$inferSelect;

function toSessionRow(row: RawSessionRow): SessionRow {
  return {
    id: row.id,
    query: row.query,
    routing: (row.routing as RoutingDecision | null) ?? null,
    finalAnswerText: row.finalAnswerText,
    consultedAgents: row.consultedAgents,
    langsmithRunId: row.langsmithRunId,
    createdAt: row.createdAt,
  };
}

function toCallRow(row: RawCallRow): SpecialistCallRow {
  return {
    id: row.id,
    agentName: row.agentName,
    subQuestion: row.subQuestion,
    findingText: row.findingText,
    citations: (row.citations as Citation[]) ?? [],
    toolCalls: (row.toolCalls as ToolCallRecord[]) ?? [],
    durationMs: row.durationMs,
    createdAt: row.createdAt,
  };
}

/** Most-recent coach sessions, newest first. */
export async function listSessions(limit = 50): Promise<SessionRow[]> {
  const db = getDb();
  const rows = await db
    .select()
    .from(coachSessions)
    .orderBy(desc(coachSessions.createdAt))
    .limit(limit);
  return rows.map(toSessionRow);
}

/** A single session with its specialist calls, or null if no such id. */
export async function getSession(id: string): Promise<SessionDetail | null> {
  const db = getDb();
  const [session] = await db
    .select()
    .from(coachSessions)
    .where(eq(coachSessions.id, id))
    .limit(1);
  if (!session) return null;

  const calls = await db
    .select()
    .from(coachSpecialistCalls)
    .where(eq(coachSpecialistCalls.sessionId, id))
    .orderBy(coachSpecialistCalls.createdAt);

  return { ...toSessionRow(session), calls: calls.map(toCallRow) };
}
